public class Main {
    public static void main(String[] args) {
        int pages = 33000;
        byte hours = 90;
        short price = 20000;
        long study = 200L;
        float temperature = 78.48f;
        double distance = 1.4567777;
        System.out.println("Значение переменной pages с типом int равно " + pages);
        System.out.println("Значение переменной hours с типом byte равно " + hours);
        System.out.println("Значение переменной price с типом short равно " + price);
        System.out.println("Значение переменной study с типом long равно " + study);
        System.out.println("Значение переменной temperature с типом float равно " + temperature);
        System.out.println("Значение переменной distance с типом double равно " + distance);
        System.out.println();
        double legLength = 27.12;
        long amountOfMoney = 987678965549L;
        float weight = 2.786f;
        short numberOfPages = 569;
        short altitude = -159;
        short sofaPrice = 27897;
        byte anymals = 67;
        System.out.println("Значение переменной legLength с типом double равно " + legLength);
        System.out.println("Значение переменной amountOfMoney с типом long равно " + amountOfMoney);
        System.out.println("Значение переменной weight с типом float равно " + weight);
        System.out.println("Значение переменной numberOfPages с типом short равно " + numberOfPages);
        System.out.println("Значение переменной altitude с типом short равно " + altitude);
        System.out.println("Значение переменной sofaPrice с типом short равно " + sofaPrice);
        System.out.println("Значение переменной anymals с типом byte равно " + anymals);
        System.out.println();
        byte studentsOfLyudmilaPavlovna = 23;
        byte studentsOfAnnaSergeevna = 27;
        byte studentsOfEkaterinaAndreevna = 30;
        int totalStudents = studentsOfLyudmilaPavlovna + studentsOfAnnaSergeevna + studentsOfEkaterinaAndreevna;
        int sheetsOfPaperForOneStudent = 480 / totalStudents;
        System.out.println("На каждого ученика рассчитано " + sheetsOfPaperForOneStudent + " листов бумаги");
        System.out.println();
        byte productivityInTwoMinutes = 16;
        int productivityInOneMinute = productivityInTwoMinutes / 2;
        int productivityInTwentyMinutes = productivityInOneMinute * 20;
        int productivityInOneDay = productivityInOneMinute * 60 * 24;
        int productivityInThreeDays = productivityInOneDay * 3;
        int productivityInOneMonth = productivityInOneDay * 30;
        System.out.println("За 20 минут машина произвела " + productivityInTwentyMinutes + " штук бутылок");
        System.out.println("За сутки машина произвела " + productivityInOneDay + " штук бутылок");
        System.out.println("За 3 дня машина произвела " + productivityInThreeDays + " штук бутылок");
        System.out.println("За 1 месяц машина произвела " + productivityInOneMonth + " штук бутылок");
        System.out.println();
        byte totalPaint = 120;
        byte whitePaintForOneClass = 2;
        byte brownPaintForOneClass = 4;
        int totalPaintForOneClass = whitePaintForOneClass + brownPaintForOneClass;
        int numberOfClasses = totalPaint / totalPaintForOneClass;
        int totalWhitePaint = whitePaintForOneClass * numberOfClasses;
        int totalBrownPaint = brownPaintForOneClass * numberOfClasses;
        System.out.println("В школе, где " + numberOfClasses + " классов, нужно " + totalWhitePaint + " банок белой краски и " + totalBrownPaint + " банок коричневой краски");
        System.out.println();
        byte weightOfOneBanana = 80;
        int weightOfAllBananas = weightOfOneBanana * 5;
        byte weightOneHundredMlMilk = 105;
        int weightOfTotalMilk = weightOneHundredMlMilk * 200 / 100;
        byte weightOneIceCream = 100;
        int weightTotalIceCream = weightOneIceCream * 2;
        byte weightOneEgg = 70;
        int weightTotalEgg = weightOneEgg * 4;
        int totalWeightG = weightOfAllBananas + weightOfTotalMilk + weightTotalIceCream + weightTotalEgg;
        float totalWeightKg = totalWeightG / 1000f;
        System.out.println("Вес спортзавтрака составляет " + totalWeightG + " грамм или " + totalWeightKg + " кг" );
        System.out.println();
        int lostWeight = 7 * 1000;
        int lostWeightInDayMin = 250;
        int lostWeightInDayMax = 500;
        int daysMax = lostWeight / lostWeightInDayMin;
        int daysMin = lostWeight / lostWeightInDayMax;
        int daysAverage = (daysMin + daysMax) / 2;
        System.out.println(daysMax + " дней уйдет на похудение, если спортсмен будет терять каждый день по 250 грамм");
        System.out.println(daysMin + " дней уйдет на похудение, если спортсмен будет терять каждый день по 500 грамм");
        System.out.println(daysAverage + " дней уйдет на похудение в среднем");
        System.out.println();
        int salaryMasha = 67760;
        int salaryDenis = 83690;
        int salaryKristina = 76230;
        int annualSalaryMasha = salaryMasha * 12;
        int annualSalaryDenis = salaryDenis * 12;
        int annualSalaryKristina = salaryKristina * 12;
        double newSalaryMasha = salaryMasha * 0.1 + salaryMasha;
        double newSalaryDenis = salaryDenis * 0.1 + salaryDenis;
        double newSalaryKristina = salaryKristina * 0.1 + salaryKristina;
        double newAnnualSalaryMasha = newSalaryMasha * 12;
        double newAnnualSalaryDenis =  newSalaryDenis * 12;
        double newAnnualSalaryKristina =  newSalaryKristina * 12;
        double increaseInAnnualSalaryMasha = newAnnualSalaryMasha - annualSalaryMasha;
        double increaseInAnnualSalaryDenis = newAnnualSalaryDenis - annualSalaryDenis;
        double increaseInAnnualSalaryKristina = newAnnualSalaryKristina - annualSalaryKristina;
        System.out.println("Маша теперь получает " + newSalaryMasha + " рублей. Годовой доход вырос на " + increaseInAnnualSalaryMasha + " рублей");
        System.out.println("Денис теперь получает " + newSalaryDenis + " рублей. Годовой доход вырос на " + increaseInAnnualSalaryDenis + " рублей");
        System.out.println("Кристина теперь получает " + newSalaryKristina + " рублей. Годовой доход вырос на " + increaseInAnnualSalaryKristina + " рублей");
    }
}